export const TEAM_FLAGS: Record<string, string> = {
  // Americas
  'Argentina': '🇦🇷',
  'Bolivia': '🇧🇴',
  'Brazil': '🇧🇷',
  'Canada': '🇨🇦',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Costa Rica': '🇨🇷',
  'Cuba': '🇨🇺',
  'Ecuador': '🇪🇨',
  'El Salvador': '🇸🇻',
  'Guatemala': '🇬🇹',
  'Haiti': '🇭🇹',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Mexico': '🇲🇽',
  'Panama': '🇵🇦',
  'Paraguay': '🇵🇾',
  'Peru': '🇵🇪',
  'Trinidad and Tobago': '🇹🇹',
  'United States': '🇺🇸',
  'Uruguay': '🇺🇾',
  'Venezuela': '🇻🇪',
  // Europe
  'Albania': '🇦🇱',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'Bosnia-Herzegovina': '🇧🇦',
  'Bosnia & Herzegovina': '🇧🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  'Croatia': '🇭🇷',
  'Czech Republic': '🇨🇿',
  'Czechia': '🇨🇿',
  'Denmark': '🇩🇰',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Greece': '🇬🇷',
  'Hungary': '🇭🇺',
  'Italy': '🇮🇹',
  'Netherlands': '🇳🇱',
  'North Macedonia': '🇲🇰',
  'Norway': '🇳🇴',
  'Poland': '🇵🇱',
  'Portugal': '🇵🇹',
  'Romania': '🇷🇴',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Serbia': '🇷🇸',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Spain': '🇪🇸',
  'Switzerland': '🇨🇭',
  'Turkey': '🇹🇷',
  'Türkiye': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Iceland': '🇮🇸',
  'Georgia': '🇬🇪',
  // Africa
  'Algeria': '🇩🇿',
  'Cameroon': '🇨🇲',
  'DR Congo': '🇨🇩',
  'Egypt': '🇪🇬',
  'Ghana': '🇬🇭',
  'Ivory Coast': '🇨🇮',
  "Côte d'Ivoire": '🇨🇮',
  'Mali': '🇲🇱',
  'Morocco': '🇲🇦',
  'Nigeria': '🇳🇬',
  'Senegal': '🇸🇳',
  'South Africa': '🇿🇦',
  'Tunisia': '🇹🇳',
  'Uganda': '🇺🇬',
  'Tanzania': '🇹🇿',
  'Zambia': '🇿🇲',
  'Kenya': '🇰🇪',
  'Angola': '🇦🇴',
  'Burkina Faso': '🇧🇫',
  'Guinea': '🇬🇳',
  'Benin': '🇧🇯',
  'Namibia': '🇳🇦',
  'Cape Verde': '🇨🇻',
  'Equatorial Guinea': '🇬🇶',
  'Gabon': '🇬🇦',
  'Comoros': '🇰🇲',
  // Asia
  'Australia': '🇦🇺',
  'Bahrain': '🇧🇭',
  'China': '🇨🇳',
  "China PR": '🇨🇳',
  'Indonesia': '🇮🇩',
  'Iran': '🇮🇷',
  'Iraq': '🇮🇶',
  'Japan': '🇯🇵',
  'Jordan': '🇯🇴',
  'North Korea': '🇰🇵',
  "Korea DPR": '🇰🇵',
  'South Korea': '🇰🇷',
  'Korea Republic': '🇰🇷',
  'Kuwait': '🇰🇼',
  'Oman': '🇴🇲',
  'Qatar': '🇶🇦',
  'Saudi Arabia': '🇸🇦',
  'Syria': '🇸🇾',
  'Thailand': '🇹🇭',
  'United Arab Emirates': '🇦🇪',
  'UAE': '🇦🇪',
  'Uzbekistan': '🇺🇿',
  'Vietnam': '🇻🇳',
  'India': '🇮🇳',
  'Palestine': '🇵🇸',
  // Oceania
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬',
  'Solomon Islands': '🇸🇧',
  // Caribbean/CONCACAF
  'Curacao': '🇨🇼',
  'Suriname': '🇸🇷',
  'Puerto Rico': '🇵🇷',
  'Guadeloupe': '🇬🇵',
  'Martinique': '🇲🇶',
}

export function getFlag(teamName: string): string {
  return TEAM_FLAGS[teamName] ?? '🏳️'
}

export const AVATAR_COLORS = [
  '#f59e0b', '#10b981', '#3b82f6', '#8b5cf6',
  '#ef4444', '#f97316', '#06b6d4', '#ec4899',
  '#84cc16', '#6366f1', '#14b8a6', '#f43f5e',
]

export function getAvatarColor(index: number): string {
  return AVATAR_COLORS[index % AVATAR_COLORS.length]
}

export const STAGES: Record<string, string> = {
  GROUP_STAGE: 'Fase de Grupos',
  LAST_32: 'Dieciseisavos',
  LAST_16: 'Octavos de Final',
  QUARTER_FINALS: 'Cuartos de Final',
  SEMI_FINALS: 'Semifinales',
  THIRD_PLACE: '3er Lugar',
  FINAL: 'Final',
}

export const STAGE_ORDER = [
  'GROUP_STAGE', 'LAST_32', 'LAST_16', 'QUARTER_FINALS', 'SEMI_FINALS', 'THIRD_PLACE', 'FINAL'
]
